spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailyreport?createDatabaseIfNotExist=true
    username: debian-sys-maint
    password: Vg1mbVYgKwABRkyN
  jpa:
    hibernate:
      ddl-auto: update
      validator:
        apply_to_ddl: true

api:
  security:
    allowedOrigins: http://localhost:5173
    token:
      secret: ${JWT_SECRET:dailyReports}

aws:
  accessKeyId:
  secretAccessKey:
  region: sa-east-1
  bucket: dailyreport-images