spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dailyreport?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      validator:
        apply_to_ddl: true